apiVersion: v1
kind: Pod
metadata:
  labels:
    env: test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: 
                operator: In 
                values:
                  - us-east-1d 
  containers:
    - name: nginx
      image: nginx                 
